/*
* TS3MassMover - Teamspeak 3 Client Plugin
*
* Copyright (c) 2010-2015 Stefan Martens, Mr. S
*/

// Automatic generated file: 22.03.2015 14:03:02,31

#ifndef PLUGINVERSION_H
#define PLUGINVERSION_H

#define VERSION_MAJOR 0 
#define VERSION_MINOR 59 
#define VERSION_BUILD 21
#define VERSION_QFE 32 

#define _STR(x) #x
#define STR(x) _STR(x)
#define VERSION_NUMBER VERSION_MAJOR,VERSION_MINOR,VERSION_BUILD,VERSION_QFE
#define VERSION_STRING STR(VERSION_MAJOR) "." STR(VERSION_MINOR) "." STR(VERSION_BUILD) "." STR(VERSION_QFE)

#define PLUGIN_VERSION VERSION_STRING
#define PLUGIN_API_VERSION VERSION_BUILD

#endif
